### ISSUE TITLE
F-14 RIO insert overlay location obsolete

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDMF#14]
for the non HiVis overlay location on the F-14 RIO, the lines for the overlays read the following:
`"fileName": "F-14\\F14 CAP Drum.jpg",`

this is an obsolete location, and the lines should read
`"fileName": "~MFDisplay_Overlays\\F14R LMFD_CAP.jpg",`

The Hivis locations are fine.

**Comment by ScottyMac52** [comment]
I put a request on the Trello board to have the location of ~MFDisplay_Overlays altered to be under the Profile JPG's folder to make it easier to consume in the JSON files.

**Comment by HomeFries94** [comment]
~MFDisplay_Overlays are located under Profile JPGs already.

**Comment by ScottyMac52** [comment]
Copy that, I wasn't sure because I had it above it as well but that could have been me.
